### ISSUE TITLE
Error with Mnemonic.fromSentence method

### ISSUE THREAD

**Issue by redDwarf03** [ethicnology/dart-bip39-mnemonic#2]
Hello

i met an issue with this case:
```
 String sentence =
          "insecte pirogue tamiser goudron torpille rejouer essieu lactose bouquin humble service dauphin gendarme fougère visqueux essence projeter thème éruption chausson incliner plastron bambin boiser";
      Mnemonic.fromSentence(sentence, Language.french);
```

i obtain this:
```
_Exception (Exception: mnemonic: "fougère" does not exist in Language.french)
```

but the word "fougère" is in the french list

**Comment by ethicnology** [comment]
As I tried to warn you in your previous [pull request](https://github.com/ethicnology/dart-bip39-mnemonic/pull/1#issuecomment-1177072601), BIP39 expects words in NFKD format, the word fougère that you tried to use doesn't contain a diacritic accent.  
```sh
Expected: 'fougère'
  Actual: 'fougère'
   Which: is different.Traduire cette page
          Expected: fougère
            Actual: fougère
                        ^
           Differ at offset 4
```

To make it easier for developers, I [pushed a refactoring](https://github.com/ethicnology/dart-bip39-mnemonic/commit/a2f73b7b2e32766a58fdaa32ec2fb06ad95a2ba0) of Mnemonic.fromSentence which formats (NFKD) each words of the inputs.

Please upgrade to 3.0.4

**Comment by redDwarf03** [comment]
thank you
