### ISSUE TITLE
Error when 2 words 

### ISSUE THREAD

**Issue by redDwarf03** [ethicnology/dart-bip39-mnemonic#5]
Hello

i don't understand why this mnemonic doesn't work with `Mnemonic.fromSentence`... 
```
raven net net pyramid must erosion fragile rack run peace recall mesh spray message noise museum safe brother like bring enhance knock embark lesson
```
but
```
raven pause net pyramid must erosion fragile rack run peace recall mesh spray message noise museum safe brother like bring enhance knock embark lesson
```
(i just change the second word.. it seems it doesn't work when we have 2 words similar)

**Comment by redDwarf03** [comment]
sorry. bad checksum..

**Comment by ethicnology** [comment]
I was writing about it, but yes two different mnemonic shouldn't share the same checksum
